apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    tier: db
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
      tier: db
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: db
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
    tier: db
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: slave
    tier: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: db
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: db
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-cloud
spec:
  type: LoadBalancer
  selector:
    app: simple-api-cloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api-cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-api-cloud
  template:
    metadata: 
      labels: 
        app: simple-api-cloud
    spec:
      containers:
      - name: api
        image: gcr.io/revolut-sre-challenge/simple-api-cloud:${TAG}
        ports:
        - containerPort: 8000


